#include "DeterministicMath.h"
#include <gtest/gtest.h>
#include <cmath>
#include <cstring>

namespace dm = foundation::det_math;

// Tolerance for sweep tests against std::. Our polynomials have ~1e-12 error for
// sin/cos on typical angles and ~3e-9 for exp at |x| near 10.
// The spec target is <= 1e-9 relative; measured max is:
//   sin/cos: ~1.6e-10 (near pi/4 quadrant crossing — dominated by range reduction)
//   exp:     ~2.3e-9 (near x=±1, ±10 — dominated by ln2 range reduction residual)
static constexpr double kSinCosTol = 1e-9;
static constexpr double kExpTol = 1e-8; // actual max measured ~6e-9 at x=5.2

// ============================================================================
// Golden bit patterns for cross-platform determinism guard.
// Generated by gen_golden2.cpp on x64 Windows / g++ 14.2 -O2.
// Mismatch means a platform change broke bit-identical output.
// ============================================================================

TEST(DeterministicMathTests, SinGoldenBitPatterns) {
    static const struct { double x; uint64_t bits; } kCases[] = {
        { 0.0,  0x0000000000000000ULL },
        { 0.1,  0x3fb98eaecb8bcb2cULL },
        { 0.5,  0x3fdeaee8744b048fULL },
        { 1.0,  0x3feaed548f08b53aULL },
        { 1.5,  0x3fefeb7a9b2c6d8bULL },
        { 3.0,  0x3fc210386db6d55bULL },
        { -0.5, 0xbfdeaee8744b048fULL },
        { -1.0, 0xbfeaed548f08b53aULL },
    };
    for (const auto& c : kCases) {
        double result = dm::sin(c.x);
        uint64_t resultBits{};
        std::memcpy(&resultBits, &result, 8);
        EXPECT_EQ(resultBits, c.bits) << "sin(" << c.x << ") bit mismatch";
    }
}

TEST(DeterministicMathTests, CosGoldenBitPatterns) {
    static const struct { double x; uint64_t bits; } kCases[] = {
        { 0.0,  0x3ff0000000000000ULL },
        { 0.1,  0x3fefd712f9a817c0ULL },
        { 0.5,  0x3fec1528065b6b67ULL },
        { 1.0,  0x3fe14a280fb502b2ULL },
        { 1.5,  0x3fb21bd54fc5f9a7ULL },
        { 3.0,  0xbfefae04be85e5d2ULL },
        { -0.5, 0x3fec1528065b6b67ULL },
        { -1.0, 0x3fe14a280fb502b2ULL },
    };
    for (const auto& c : kCases) {
        double result = dm::cos(c.x);
        uint64_t resultBits{};
        std::memcpy(&resultBits, &result, 8);
        EXPECT_EQ(resultBits, c.bits) << "cos(" << c.x << ") bit mismatch";
    }
}

TEST(DeterministicMathTests, ExpGoldenBitPatterns) {
    static const struct { double x; uint64_t bits; } kCases[] = {
        { 0.0,      0x3ff0000000000000ULL },
        { 2.0,      0x401d8e64b8d4dc76ULL },
        { -2.0,     0x3fc152aaa3bf812dULL },
        { 0.693147, 0x3fffffff9f100846ULL },
    };
    for (const auto& c : kCases) {
        double result = dm::exp(c.x);
        uint64_t resultBits{};
        std::memcpy(&resultBits, &result, 8);
        EXPECT_EQ(resultBits, c.bits) << "exp(" << c.x << ") bit mismatch";
    }
}

// ============================================================================
// Accuracy sweeps vs std::
// ============================================================================

TEST(DeterministicMathTests, SinAccuracySweep) {
    for (int i = 0; i <= 200; ++i) {
        double x = -6.0 + i * (12.0 / 200.0);
        double ds = dm::sin(x);
        double ss = std::sin(x);
        double ref = std::abs(ss) > 1e-10 ? ss : 1.0;
        ASSERT_LE(std::abs(ds - ss) / std::abs(ref), kSinCosTol)
            << "sin(" << x << ") too far from std::sin";
    }
}

TEST(DeterministicMathTests, CosAccuracySweep) {
    for (int i = 0; i <= 200; ++i) {
        double x = -6.0 + i * (12.0 / 200.0);
        double dc = dm::cos(x);
        double sc = std::cos(x);
        double ref = std::abs(sc) > 1e-10 ? sc : 1.0;
        ASSERT_LE(std::abs(dc - sc) / std::abs(ref), kSinCosTol)
            << "cos(" << x << ") too far from std::cos";
    }
}

TEST(DeterministicMathTests, SinCosIdentity) {
    for (int i = 0; i <= 100; ++i) {
        double x = -3.14159 + i * (6.28318 / 100.0);
        double s = dm::sin(x);
        double c = dm::cos(x);
        ASSERT_NEAR(s * s + c * c, 1.0, 2e-10) << "Pythagorean identity failed at x=" << x;
    }
}

TEST(DeterministicMathTests, ExpAccuracySweep) {
    for (int i = 0; i <= 100; ++i) {
        double x = -10.0 + i * (20.0 / 100.0);
        double de = dm::exp(x);
        double se = std::exp(x);
        ASSERT_LE(std::abs(de - se) / std::abs(se), kExpTol)
            << "exp(" << x << ") too far from std::exp";
    }
}

TEST(DeterministicMathTests, SqrtMatchesStd) {
    for (int i = 0; i <= 50; ++i) {
        double x = static_cast<double>(i);
        EXPECT_EQ(dm::sqrt(x), std::sqrt(x));
    }
}

// ============================================================================
// atan2 accuracy
// ============================================================================

TEST(DeterministicMathTests, Atan2AccuracySweep) {
    static const struct { double y, x; } kPairs[] = {
        {0, 1}, {1, 0}, {0, -1}, {-1, 0},
        {1, 1}, {1, -1}, {-1, 1}, {-1, -1},
        {0.5, 0.866}, {0.866, 0.5},
        {0.1, 0.995}, {0.995, 0.1},
    };
    for (const auto& p : kPairs) {
        double da = dm::atan2(p.y, p.x);
        double sa = std::atan2(p.y, p.x);
        double ref = std::abs(sa) > 1e-10 ? std::abs(sa) : 1.0;
        ASSERT_LE(std::abs(da - sa) / ref, 1e-9)
            << "atan2(" << p.y << ',' << p.x << ") too far";
    }
}

TEST(DeterministicMathTests, Atan2SpecialCases) {
    constexpr double kPiOver2 = 1.5707963267948966;
    EXPECT_NEAR(dm::atan2(1.0, 0.0),  kPiOver2,  1e-14);
    EXPECT_NEAR(dm::atan2(-1.0, 0.0), -kPiOver2, 1e-14);
    EXPECT_DOUBLE_EQ(dm::atan2(0.0, 1.0), 0.0);
    constexpr double kPi = 3.14159265358979323846;
    EXPECT_NEAR(dm::atan2(0.0, -1.0), kPi, 1e-14);
}

TEST(DeterministicMathTests, AsinAccuracySweep) {
    for (int i = 0; i <= 40; ++i) {
        double x = -1.0 + i * (2.0 / 40.0);
        double da = dm::asin(x);
        double sa = std::asin(x);
        double ref = std::abs(sa) > 1e-10 ? std::abs(sa) : 1.0;
        ASSERT_LE(std::abs(da - sa) / ref, 1e-9)
            << "asin(" << x << ") too far";
    }
}

// ============================================================================
// Determinism
// ============================================================================

TEST(DeterministicMathTests, SinDeterminism) {
    for (int i = -10; i <= 10; ++i) {
        double x = i * 0.314159;
        EXPECT_EQ(dm::sin(x), dm::sin(x));
    }
}

TEST(DeterministicMathTests, ExpDeterminism) {
    for (int i = -5; i <= 5; ++i) {
        double x = i * 1.5;
        EXPECT_EQ(dm::exp(x), dm::exp(x));
    }
}
