// ApronField seam tests (terrain-polygons-architecture.md D4/D14): two chunks
// built independently on separate "workers" must see bit-identical tiles across
// their shared border. ApronField never touches a neighbor Chunk directly (it
// can't: generation runs before neighbors necessarily exist); it reconstructs
// what the neighbor would compute from the generating chunk's own sample data.
// These tests generate the real neighbor chunks too, so the comparison is a
// genuine cross-check of two independent computations, not a tautology.

#include "ApronField.h"

#include "world/chunk/Chunk.h"
#include "world/chunk/ChunkCoordinate.h"
#include "world/chunk/ChunkSampleResult.h"
#include "world/chunk/MockWorldSampler.h"

#include <gtest/gtest.h>

#include <memory>
#include <unordered_map>

using namespace engine::world;

namespace {

// Generate a chunk the same way ChunkManager would: sample, construct, generate().
std::unique_ptr<Chunk> generateChunk(const MockWorldSampler& sampler, ChunkCoordinate coord) {
	ChunkSampleResult sample = sampler.sampleChunk(coord);
	auto chunk = std::make_unique<Chunk>(coord, std::move(sample), sampler.getWorldSeed());
	chunk->generate();
	return chunk;
}

// Which neighbor chunk (offset dx, dy from the apron-owning chunk) owns extended-
// region coordinate (ex, ey), and that neighbor's own local tile coordinates.
// Mirrors the mapping ApronField::build uses internally (ApronField.cpp).
struct OwningNeighbor {
	int32_t dx;
	int32_t dy;
	uint16_t nx;
	uint16_t ny;
};

OwningNeighbor owningNeighbor(int32_t ex, int32_t ey) {
	const int32_t lx = ex - kApronTiles;
	const int32_t ly = ey - kApronTiles;
	const int32_t dx = (lx < 0) ? -1 : ((lx >= kChunkSize) ? 1 : 0);
	const int32_t dy = (ly < 0) ? -1 : ((ly >= kChunkSize) ? 1 : 0);
	return {dx, dy, static_cast<uint16_t>(lx - dx * kChunkSize), static_cast<uint16_t>(ly - dy * kChunkSize)};
}

// Compare an apron tile against the real generated neighbor's tile: everything
// but adjacency (apron tiles never get adjacency, D2), and surface only when the
// neighbor's mud pass didn't touch it. TilePostProcessor::generateMud is the only
// thing besides adjacency that a post-generate() tile can differ from its raw
// computeTileFrom() output in (it only ever overwrites `surface` to Mud), so
// skipping the surface check exactly when the real tile reads Mud is exact, not
// an approximation.
void expectApronTileMatchesNeighbor(const TileData& apronTile, const TileData& neighborTile) {
	EXPECT_EQ(apronTile.primaryBiome, neighborTile.primaryBiome);
	EXPECT_EQ(apronTile.secondaryBiome, neighborTile.secondaryBiome);
	EXPECT_EQ(apronTile.biomeBlend, neighborTile.biomeBlend);
	EXPECT_EQ(apronTile.elevation, neighborTile.elevation);
	EXPECT_EQ(apronTile.moisture, neighborTile.moisture);
	EXPECT_EQ(apronTile.waterDepth, neighborTile.waterDepth);
	if (neighborTile.surface != Surface::Mud) {
		EXPECT_EQ(apronTile.surface, neighborTile.surface);
	}
}

} // namespace

// Chunk (0,0)'s apron across its east, south, and southeast borders must match
// the real east/south/southeast neighbor chunks tile-for-tile.
TEST(ApronFieldTest, MatchesRealNeighborsAcrossEastSouthSoutheastBorders) {
	MockWorldSampler sampler(12345);
	const ChunkCoordinate origin{0, 0};

	std::unique_ptr<Chunk> chunk00 = generateChunk(sampler, origin);

	std::unordered_map<ChunkCoordinate, std::unique_ptr<Chunk>> neighbors;
	for (const ChunkCoordinate& c : {ChunkCoordinate{1, 0}, ChunkCoordinate{0, 1}, ChunkCoordinate{1, 1}}) {
		neighbors[c] = generateChunk(sampler, c);
	}

	ApronField apron = ApronField::build(origin, chunk00->biomeData(), sampler.getWorldSeed());

	int checked = 0;
	for (int32_t ey = 0; ey < kExtendedSize; ++ey) {
		for (int32_t ex = 0; ex < kExtendedSize; ++ex) {
			const int32_t lx = ex - kApronTiles;
			const int32_t ly = ey - kApronTiles;
			const bool inInterior = lx >= 0 && lx < kChunkSize && ly >= 0 && ly < kChunkSize;
			if (inInterior) {
				continue; // chunk's own tile, not apron
			}

			const OwningNeighbor owner = owningNeighbor(ex, ey);
			const auto it = neighbors.find(ChunkCoordinate{origin.x + owner.dx, origin.y + owner.dy});
			if (it == neighbors.end()) {
				continue; // west/north/nw/ne/sw neighbor not generated by this test
			}

			expectApronTileMatchesNeighbor(apron.tileAt(ex, ey), it->second->getTile(owner.nx, owner.ny));
			++checked;
		}
	}

	// East strip (8 x 512) + south strip (512 x 8) + southeast corner (8 x 8).
	constexpr int kExpected = kApronTiles * kChunkSize * 2 + kApronTiles * kApronTiles;
	EXPECT_EQ(checked, kExpected) << "the east/south/southeast portion of the ring must be fully exercised";
}

// Negative chunk coordinates: chunk (-1,-1)'s apron reaches across its southeast
// corner into chunk (0,0). Exercises negative coordinate arithmetic in both the
// neighborhood corner lattice (world position = (coord.x - 1 + li) * chunkSize,
// which goes further negative here) and ApronField's neighbor-offset math.
TEST(ApronFieldTest, NegativeCoordinateNeighborMatches) {
	MockWorldSampler sampler(777);
	const ChunkCoordinate origin{-1, -1};
	const ChunkCoordinate southeast{0, 0};

	std::unique_ptr<Chunk> chunkNeg = generateChunk(sampler, origin);
	std::unique_ptr<Chunk> chunkSE = generateChunk(sampler, southeast);

	ApronField apron = ApronField::build(origin, chunkNeg->biomeData(), sampler.getWorldSeed());

	int checked = 0;
	for (int32_t ey = kApronTiles + kChunkSize; ey < kExtendedSize; ++ey) {
		for (int32_t ex = kApronTiles + kChunkSize; ex < kExtendedSize; ++ex) {
			const OwningNeighbor owner = owningNeighbor(ex, ey);
			ASSERT_EQ(owner.dx, 1);
			ASSERT_EQ(owner.dy, 1);
			expectApronTileMatchesNeighbor(apron.tileAt(ex, ey), chunkSE->getTile(owner.nx, owner.ny));
			++checked;
		}
	}
	EXPECT_EQ(checked, kApronTiles * kApronTiles);
}

// ExtendedTiles reads the chunk's own interior from Chunk::getTile and falls back
// to the apron everywhere else, with no seam at the interior/apron boundary.
TEST(ApronFieldTest, ExtendedTilesCoversInteriorAndApronWithNoGap) {
	MockWorldSampler sampler(42);
	const ChunkCoordinate origin{3, -2};

	std::unique_ptr<Chunk> chunk = generateChunk(sampler, origin);
	ApronField apron = ApronField::build(origin, chunk->biomeData(), sampler.getWorldSeed());
	ExtendedTiles extended(*chunk, apron);

	// Interior: must read the chunk's own (post-mud, post-adjacency) tile.
	EXPECT_EQ(&extended.at(kApronTiles, kApronTiles), &chunk->getTile(0, 0));
	EXPECT_EQ(&extended.at(kApronTiles + kChunkSize - 1, kApronTiles + kChunkSize - 1),
	          &chunk->getTile(kChunkSize - 1, kChunkSize - 1));

	// Just outside the interior on every side: must read the apron store, and the
	// call must not assert/crash at any of the four boundary crossings.
	(void)extended.at(kApronTiles - 1, kApronTiles);
	(void)extended.at(kApronTiles + kChunkSize, kApronTiles);
	(void)extended.at(kApronTiles, kApronTiles - 1);
	(void)extended.at(kApronTiles, kApronTiles + kChunkSize);
}
