#!/bin/bash
#
# Pre-commit hook - runs linting on staged files
#

# Run lint script on staged files
./scripts/lint.sh --staged

# Propagate exit code from lint script
# If formatting fails, block the commit
exit $?
