#!/bin/bash
#
# Pre-commit hook - Auto-format staged C++ files before commit
#
# This hook runs clang-format on staged files and re-stages them.
# The formatted files will be included in the commit.
#

set -e

# Run lint script on staged files
# This will format files and re-add them to the index
./scripts/lint.sh --staged
