#include "HashNoise.h"
#include <gtest/gtest.h>
#include <cmath>
#include <cstring>
#include <limits>

using namespace foundation;

// ============================================================================
// Hash3 — golden values generated by gen_golden2.cpp
// ============================================================================

TEST(HashNoiseTests, Hash3GoldenValues) {
    EXPECT_EQ(hash3(0, 0, 0, 0),           0xbb866a70u);
    EXPECT_EQ(hash3(1, 2, 3, 42),          0xc95b7317u);
    EXPECT_EQ(hash3(-5, 10, -3, 1),        0xa40d612au);
    EXPECT_EQ(hash3(100, 200, 300, 0xDEADBEEFu), 0xeccc242du);
}

TEST(HashNoiseTests, Hash3NonZeroForAllZeroInput) {
    // Fixed-point guard: all-zero inputs must not return zero
    EXPECT_NE(hash3(0, 0, 0, 0), 0u);
}

TEST(HashNoiseTests, Hash3Avalanche) {
    // Flipping one input bit should change ~50% of output bits on average.
    // Test that at least some bits differ for any single-input change.
    uint32_t base = hash3(5, 10, 15, 7);
    EXPECT_NE(hash3(4, 10, 15, 7), base); // x differs
    EXPECT_NE(hash3(5, 11, 15, 7), base); // y differs
    EXPECT_NE(hash3(5, 10, 14, 7), base); // z differs
    EXPECT_NE(hash3(5, 10, 15, 6), base); // seed differs
}

TEST(HashNoiseTests, Hash3OrderSensitive) {
    // Swapping x and y should give different output (order matters)
    EXPECT_NE(hash3(1, 2, 3, 0), hash3(2, 1, 3, 0));
    EXPECT_NE(hash3(1, 2, 3, 0), hash3(1, 3, 2, 0));
}

TEST(HashNoiseTests, Hash3Determinism) {
    for (int i = 0; i < 100; ++i) {
        EXPECT_EQ(hash3(i, -i, i*2, static_cast<uint32_t>(i)),
                  hash3(i, -i, i*2, static_cast<uint32_t>(i)));
    }
}

// ============================================================================
// ValueNoise3
// ============================================================================

TEST(HashNoiseTests, ValueNoise3GoldenBits) {
    // Store expected float bit patterns for cross-platform determinism check.
    // Generated by gen_golden2.cpp on x64 g++ -O2.
    auto checkBits = [](float actual, uint32_t expectedBits, const char* label) {
        uint32_t actualBits{};
        std::memcpy(&actualBits, &actual, 4);
        EXPECT_EQ(actualBits, expectedBits) << "bit mismatch: " << label;
    };
    checkBits(valueNoise3(0.5F, 0.5F, 0.5F, 0),          0x3edded44u, "0.5,0.5,0.5,0");
    checkBits(valueNoise3(1.7F, 2.3F, -0.8F, 42),         0x3e93dec1u, "1.7,2.3,-0.8,42");
    checkBits(valueNoise3(-3.14F, 2.72F, 1.41F, 999),      0x3e489648u, "-3.14,2.72,1.41,999");
}

TEST(HashNoiseTests, ValueNoise3RangeOver3DGrid) {
    // Sweep a grid and verify output is in [0, 1)
    for (int ix = -5; ix <= 5; ++ix) {
        for (int iy = -5; iy <= 5; ++iy) {
            for (int iz = -3; iz <= 3; ++iz) {
                float x = static_cast<float>(ix) * 0.31F + 0.17F;
                float y = static_cast<float>(iy) * 0.31F + 0.17F;
                float z = static_cast<float>(iz) * 0.31F + 0.17F;
                float v = valueNoise3(x, y, z, 42);
                ASSERT_GE(v, 0.0F) << "below 0 at " << x << ',' << y << ',' << z;
                ASSERT_LT(v, 1.0F) << "at or above 1 at " << x << ',' << y << ',' << z;
                ASSERT_FALSE(std::isnan(v)) << "NaN at " << x << ',' << y << ',' << z;
            }
        }
    }
}

TEST(HashNoiseTests, ValueNoise3Determinism) {
    EXPECT_EQ(valueNoise3(1.23F, -4.56F, 7.89F, 13),
              valueNoise3(1.23F, -4.56F, 7.89F, 13));
}

// ============================================================================
// GradientNoise3
// ============================================================================

TEST(HashNoiseTests, GradientNoise3GoldenBits) {
    auto checkBits = [](float actual, uint32_t expectedBits, const char* label) {
        uint32_t actualBits{};
        std::memcpy(&actualBits, &actual, 4);
        EXPECT_EQ(actualBits, expectedBits) << "bit mismatch: " << label;
    };
    checkBits(gradientNoise3(0.5F, 0.5F, 0.5F, 0),         0x3e000000u, "0.5,0.5,0.5,0");
    checkBits(gradientNoise3(1.7F, 2.3F, -0.8F, 42),        0xbd446836u, "1.7,2.3,-0.8,42");
    checkBits(gradientNoise3(-3.14F, 2.72F, 1.41F, 999),    0xbe496b28u, "-3.14,2.72,1.41,999");
}

TEST(HashNoiseTests, GradientNoise3BoundsOver3DGrid) {
    // Gradient noise is not strictly bounded to [-1,1] for all lattice alignments,
    // but for well-distributed inputs it stays well within that range.
    int nanCount = 0;
    for (int ix = -8; ix <= 8; ++ix) {
        for (int iy = -8; iy <= 8; ++iy) {
            for (int iz = -4; iz <= 4; ++iz) {
                float x = static_cast<float>(ix) * 0.37F + 0.13F;
                float y = static_cast<float>(iy) * 0.37F + 0.13F;
                float z = static_cast<float>(iz) * 0.37F + 0.13F;
                float v = gradientNoise3(x, y, z, 77);
                if (std::isnan(v)) nanCount++;
                ASSERT_GE(v, -1.5F) << "far out of range below at " << x << ',' << y << ',' << z;
                ASSERT_LE(v,  1.5F) << "far out of range above at " << x << ',' << y << ',' << z;
            }
        }
    }
    EXPECT_EQ(nanCount, 0) << "NaN found in gradient noise grid";
}

TEST(HashNoiseTests, GradientNoise3Determinism) {
    EXPECT_EQ(gradientNoise3(0.5F, 1.5F, 2.5F, 99),
              gradientNoise3(0.5F, 1.5F, 2.5F, 99));
}

// ============================================================================
// FractalNoise3 / RidgedNoise3
// ============================================================================

TEST(HashNoiseTests, FractalNoise3NoNanOverGrid) {
    for (int ix = -5; ix <= 5; ++ix) {
        for (int iy = -5; iy <= 5; ++iy) {
            float x = static_cast<float>(ix) * 0.5F;
            float y = static_cast<float>(iy) * 0.5F;
            float v = fractalNoise3(x, y, 0.0F, 0, 4, 2.0F, 0.5F);
            ASSERT_FALSE(std::isnan(v)) << "NaN at " << x << ',' << y;
        }
    }
}

TEST(HashNoiseTests, RidgedNoise3NoNanOverGrid) {
    for (int ix = -5; ix <= 5; ++ix) {
        for (int iy = -5; iy <= 5; ++iy) {
            float x = static_cast<float>(ix) * 0.5F;
            float y = static_cast<float>(iy) * 0.5F;
            float v = ridgedNoise3(x, y, 0.0F, 0, 4, 2.0F, 0.5F);
            ASSERT_FALSE(std::isnan(v)) << "NaN at " << x << ',' << y;
        }
    }
}

TEST(HashNoiseTests, FractalNoise3Determinism) {
    EXPECT_EQ(fractalNoise3(1.0F, 2.0F, 3.0F, 42, 4, 2.0F, 0.5F),
              fractalNoise3(1.0F, 2.0F, 3.0F, 42, 4, 2.0F, 0.5F));
}

TEST(HashNoiseTests, RidgedNoise3NonNegativeTendency) {
    // Ridged noise = 1 - |gradient|, so values should be mostly positive
    int positiveCount = 0;
    int total = 0;
    for (int ix = -10; ix <= 10; ++ix) {
        for (int iy = -10; iy <= 10; ++iy) {
            float v = ridgedNoise3(static_cast<float>(ix) * 0.3F,
                                   static_cast<float>(iy) * 0.3F, 0.0F, 0, 3, 2.0F, 0.5F);
            if (v > 0.0F) positiveCount++;
            total++;
        }
    }
    // Ridged noise should be positive more than 70% of the time (fBm weighting keeps it positive)
    EXPECT_GT(positiveCount, total * 7 / 10);
}

// ============================================================================
// Negative-integer boundary continuity regression
// Ensures the floor fix doesn't create discontinuities at negative integer inputs.
// ============================================================================

TEST(HashNoiseTests, ValueNoise3ContinuityAcrossNegativeInteger) {
    // Sample at -3.0 and just either side; the difference must be small (< 0.05)
    // A broken floor would assign -3.0 to cell -4 while -3.0+eps is in cell -3,
    // causing a jump equal to the difference between two uncorrelated lattice values.
    const uint32_t seed = 42;
    float at  = valueNoise3(-3.0F,  0.5F, 0.5F, seed);
    float low = valueNoise3(-3.0F - 1e-3F, 0.5F, 0.5F, seed);
    float hi  = valueNoise3(-3.0F + 1e-3F, 0.5F, 0.5F, seed);
    EXPECT_LT(std::abs(at - low), 0.05F) << "discontinuity at negative-integer boundary (low side)";
    EXPECT_LT(std::abs(at - hi),  0.05F) << "discontinuity at negative-integer boundary (high side)";
}

TEST(HashNoiseTests, GradientNoise3ContinuityAcrossNegativeInteger) {
    const uint32_t seed = 42;
    float at  = gradientNoise3(-3.0F, 0.5F, 0.5F, seed);
    float low = gradientNoise3(-3.0F - 1e-3F, 0.5F, 0.5F, seed);
    float hi  = gradientNoise3(-3.0F + 1e-3F, 0.5F, 0.5F, seed);
    EXPECT_LT(std::abs(at - low), 0.05F) << "discontinuity at negative-integer boundary (low side)";
    EXPECT_LT(std::abs(at - hi),  0.05F) << "discontinuity at negative-integer boundary (high side)";
}
