#include "SplitMix64.h"
#include "Pcg32.h"
#include <gtest/gtest.h>

using namespace foundation;

// ============================================================================
// SplitMix64 golden values
// Verified against the reference C implementation of Steele et al. 2014 and
// an independent Python port. Generated by gen_golden.cpp in TEMP/.
// ============================================================================

TEST(SplitMix64Tests, GoldenValuesFromZero) {
    uint64_t s = 0;
    s = splitMix64(s); EXPECT_EQ(s, 0xe220a8397b1dcdafULL);
    s = splitMix64(s); EXPECT_EQ(s, 0xa706dd2f4d197e6fULL);
    s = splitMix64(s); EXPECT_EQ(s, 0x238275bc38fcbe91ULL);
    s = splitMix64(s); EXPECT_EQ(s, 0x2130748aaac80268ULL);
    s = splitMix64(s); EXPECT_EQ(s, 0x78ae5a9a6b5fd45eULL);
    s = splitMix64(s); EXPECT_EQ(s, 0xcbd37ad29b93b094ULL);
    s = splitMix64(s); EXPECT_EQ(s, 0x09bb71fb54596258ULL);
    s = splitMix64(s); EXPECT_EQ(s, 0x7f4081eef340e920ULL);
}

TEST(SplitMix64Tests, GoldenSeed1) {
    constexpr uint64_t result = splitMix64(1ULL);
    EXPECT_EQ(result, 0x910a2dec89025cc1ULL);
}

TEST(SplitMix64Tests, Constexpr) {
    // Ensure constexpr evaluation compiles and matches runtime
    constexpr uint64_t compileTime = splitMix64(0ULL);
    EXPECT_EQ(compileTime, 0xe220a8397b1dcdafULL);
}

TEST(SplitMix64Tests, DeriveSeedIndependence) {
    uint64_t s0 = deriveSeed(42, 0);
    uint64_t s1 = deriveSeed(42, 1);
    uint64_t s2 = deriveSeed(42, 2);
    EXPECT_NE(s0, s1);
    EXPECT_NE(s1, s2);
    EXPECT_NE(s0, s2);

    // Reproducible
    EXPECT_EQ(deriveSeed(42, 0), s0);
    EXPECT_EQ(deriveSeed(42, 1), s1);
}

TEST(SplitMix64Tests, DeriveSeedDifferentWorldSeeds) {
    EXPECT_NE(deriveSeed(0, 0), deriveSeed(1, 0));
}

TEST(SplitMix64Tests, DeriveSeedNonTrivialForZero) {
    // streamId=0 must not return the world seed verbatim
    EXPECT_NE(deriveSeed(0, 0), 0ULL);
    EXPECT_NE(deriveSeed(1, 0), 1ULL);
}

// ============================================================================
// Pcg32 golden values — generated by same gen_golden.cpp
// ============================================================================

TEST(Pcg32Tests, GoldenSeed0) {
    Pcg32 rng(0);
    EXPECT_EQ(rng.nextUInt32(), 0x347e36a9u);
    EXPECT_EQ(rng.nextUInt32(), 0x26f7b671u);
    EXPECT_EQ(rng.nextUInt32(), 0x11b8d67cu);
    EXPECT_EQ(rng.nextUInt32(), 0x681095dau);
    EXPECT_EQ(rng.nextUInt32(), 0x13714df5u);
    EXPECT_EQ(rng.nextUInt32(), 0x7634ce67u);
    EXPECT_EQ(rng.nextUInt32(), 0x86f4989bu);
    EXPECT_EQ(rng.nextUInt32(), 0xeffb27e7u);
}

TEST(Pcg32Tests, GoldenSeed1) {
    Pcg32 rng(1);
    EXPECT_EQ(rng.nextUInt32(), 0xae073f5cu);
    EXPECT_EQ(rng.nextUInt32(), 0x039e3aa6u);
    EXPECT_EQ(rng.nextUInt32(), 0xf59e64dcu);
    EXPECT_EQ(rng.nextUInt32(), 0x94c9c79eu);
    EXPECT_EQ(rng.nextUInt32(), 0xea9f2f4du);
    EXPECT_EQ(rng.nextUInt32(), 0x97ce1e55u);
    EXPECT_EQ(rng.nextUInt32(), 0x983dcaf5u);
    EXPECT_EQ(rng.nextUInt32(), 0xa60d5d30u);
}

TEST(Pcg32Tests, NextFloatInRange) {
    Pcg32 rng(12345);
    for (int i = 0; i < 10000; ++i) {
        float f = rng.nextFloat();
        EXPECT_GE(f, 0.0F);
        EXPECT_LT(f, 1.0F);
    }
}

TEST(Pcg32Tests, NextDoubleInRange) {
    Pcg32 rng(99);
    for (int i = 0; i < 10000; ++i) {
        double d = rng.nextDouble();
        EXPECT_GE(d, 0.0);
        EXPECT_LT(d, 1.0);
    }
}

TEST(Pcg32Tests, NextRangeUniform) {
    Pcg32 rng(777);
    constexpr uint32_t kBound = 10;
    constexpr int kSamples = 1000000;
    int counts[kBound] = {};
    for (int i = 0; i < kSamples; ++i) {
        uint32_t v = rng.nextRange(kBound);
        ASSERT_LT(v, kBound);
        counts[v]++; // NOLINT(cppcoreguidelines-pro-bounds-constant-array-index)
    }
    for (uint32_t b = 0; b < kBound; ++b) {
        EXPECT_GT(counts[b], 95000) << "bucket " << b;  // NOLINT(cppcoreguidelines-pro-bounds-constant-array-index)
        EXPECT_LT(counts[b], 105000) << "bucket " << b; // NOLINT(cppcoreguidelines-pro-bounds-constant-array-index)
    }
}

TEST(Pcg32Tests, NextRangeBound1AlwaysZero) {
    Pcg32 rng(0);
    for (int i = 0; i < 100; ++i) {
        EXPECT_EQ(rng.nextRange(1), 0u);
    }
}

TEST(Pcg32Tests, Determinism) {
    Pcg32 a(42), b(42);
    for (int i = 0; i < 1000; ++i) {
        EXPECT_EQ(a.nextUInt32(), b.nextUInt32());
    }
}
