#pragma once

// GroundcoverRenderer - role==Groundcover GPU-instanced path.
// Groundcover entities are SKIPPED by the baked path (their template lookup returns null
// during bake) and drawn here instead. Each placed tuft is one instance of one of the
// asset's procedural variant meshes (generated by AssetRegistry::buildMesh per seed, so
// ALL look/feel lives in the asset), chosen by position hash. Dense grass costs a shared
// mesh + per-instance data, and a tunable zoom LOD fades it out when blades shrink below a
// few px on screen (the grass tile texture carries it from there).

#include "assets/placement/PlacementExecutor.h"
#include "primitives/InstanceData.h"
#include "world/camera/WorldCamera.h"
#include "world/chunk/ChunkCoordinate.h"
#include "world/rendering/InstancingUniforms.h"

#include <cstdint>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

namespace engine::world {

/// Draws groundcover (grass) for the visible chunks via GPU instancing, with the zoom LOD.
class GroundcoverRenderer {
  public:
	void render(
		const assets::PlacementExecutor&		   executor,
		const std::unordered_set<ChunkCoordinate>& processedChunks,
		const WorldCamera&						   camera,
		int										   viewportWidth,
		int										   viewportHeight,
		float									   pixelsPerMeter,
		uint64_t								   frameCounter,
		InstancingUniforms&						   uniforms,
		RenderStats&							   stats
	);

	/// Release uploaded variant meshes on teardown.
	~GroundcoverRenderer();

	/// Evict cached chunk instance buckets not recently visible (mirrors the baked LRU) so the
	/// per-chunk InstanceData cache does not grow unbounded over a long pan/play session.
	void evictLRU(const std::unordered_set<ChunkCoordinate>& processedChunks);

  private:
	// LRU bound: keep recently-visible chunks' instance buckets; evict oldest beyond the cap.
	static constexpr size_t kMaxCachedChunks = 64;
	static constexpr size_t kEvictionBatchSize = 8;

	/// Per-chunk groundcover instances: defName -> per-variant instance buckets. Built lazily
	/// from the placement spatial index the first time a chunk is drawn.
	struct GroundcoverChunkCache {
		std::unordered_map<std::string, std::vector<std::vector<Renderer::InstanceData>>> byDef;
		float	 minX = 0, minY = 0, maxX = 0, maxY = 0; // world bounds for culling
		uint64_t lastAccessFrame = 0;
		bool	 built = false;
	};
	std::unordered_map<ChunkCoordinate, GroundcoverChunkCache> m_groundcoverChunkCache;

	/// Per-defName uploaded variant mesh handles, generated lazily from the asset
	/// (AssetRegistry::buildMesh per seed) so all look/feel stays in the asset, not engine C++.
	std::unordered_map<std::string, std::vector<Renderer::InstancedMeshHandle>> m_groundcoverHandles;

	/// Generate (once, lazily) and return a groundcover asset's variant mesh handles.
	const std::vector<Renderer::InstancedMeshHandle>& ensureGroundcoverVariants(const std::string& defName);

	/// Build one chunk's groundcover instance buckets from the spatial index.
	void buildGroundcoverChunk(const assets::PlacementExecutor& executor, const ChunkCoordinate& coord, GroundcoverChunkCache& cache);
};

}  // namespace engine::world
