name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build clang

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: '8f54ef5453e7e76ff01e15988bf243e7247c5eb5'

    - name: Configure CMake
      run: |
        cmake -S . -B build \
          -G Ninja \
          -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake \
          -DBUILD_TESTING=ON
      env:
        CC: clang
        CXX: clang++

    - name: Build
      run: cmake --build build -j$(nproc)

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure -E ".*\.bench"
      env:
        CTEST_OUTPUT_ON_FAILURE: 1

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: build/Testing/
        retention-days: 7
